# Generated by Django 5.1.1 on 2024-10-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_admin', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=100)),
                ('mot_de_passe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_materiel', models.CharField(max_length=100, unique=True)),
                ('nom_materiel', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=10)),
                ('id_admin', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('emprunte', 'Emprunté'), ('rendu', 'Rendu')], default='disponible', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisation',
            fields=[
                ('id_utils', models.AutoField(primary_key=True, serialize=False)),
                ('id_admin', models.CharField(max_length=100)),
                ('id_materiel', models.CharField(max_length=100)),
                ('id_etudiant', models.CharField(max_length=100)),
            ],
        ),
    ]
