# Generated by Django 5.1.1 on 2024-10-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiel',
            name='id',
        ),
        migrations.AlterField(
            model_name='materiel',
            name='id_materiel',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
