# Generated by Django 5.1.1 on 2024-10-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_materiel_id_alter_materiel_id_materiel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='id_materiel',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='status',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('utilise', 'Utilisé'), ('rendu', 'Rendu')], default='disponible', max_length=10),
        ),
    ]
