# Generated by Django 5.1.1 on 2024-11-04 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_materiel_id_materiel_alter_materiel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='fonction',
        ),
        migrations.RemoveField(
            model_name='utilisation',
            name='id_etudiant',
        ),
        migrations.AddField(
            model_name='admin',
            name='photo_admin',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='utilisation',
            name='dateRendu',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisation',
            name='date_debut',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='utilisation',
            name='date_fin_prevu',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='utilisation',
            name='estRendu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisation',
            name='matricule',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='utilisation',
            name='niveau',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='utilisation',
            name='nom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='utilisation',
            name='telephone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='admin',
            name='mot_de_passe',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='admin',
            name='nom_admin',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='id_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.admin'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='nom_materiel',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='nombre',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='utilisation',
            name='id_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.admin'),
        ),
        migrations.AlterField(
            model_name='utilisation',
            name='id_materiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.materiel'),
        ),
    ]
