# Generated by Django 5.1.1 on 2024-11-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_admin_fonction_remove_utilisation_id_etudiant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='status',
            field=models.CharField(default='disponible', max_length=10),
        ),
    ]
